### ISSUE TITLE
Ai question 

### ISSUE THREAD

**Issue by anisc** [OMerkel/Scopa#1]
What would be the best solution to create a variable strength ai ?

**Comment by OMerkel** [comment]
This strongly depends on the algorithm used for the AI. E.g. a Minimax or alike algorithm could use a maximum look ahead level. While a MCTS algorithm could simply be influenced by the maximum amount of game simulations.

Another approach could be to simply implement multiple AI engines based on different algorithms. Depending on the game these might be more or less successful.

Next you could use machine learning approaches. The different AI strength can then be implemented by the amount of training rounds/iterations or depth of learning with a given training data set.
